name: Tag a Release

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Tag Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
            
            - name: Get Version
              run: echo "REL_VERSION=$(cat ./version)" >> $GITHUB_ENV
              
            - name: Create release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: v${{ env.REL_VERSION }}
                release_name: v${{ env.REL_VERSION }}
                body: |
                  | Ticket # | Feature | Completed By |
                  | :---: | --- | --- |
